steps:
  - id: build image
    name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - --push
      - '-t'
      - northamerica-northeast1-docker.pkg.dev/vksuy-dav-svc-prj-7b5e/vks-docker-repo-front/auto_srt_front:${_DOCKER_TAG}
      - .
substitutions:
    _DOCKER_TAG: v1.0.0